export const ADD_CENTER_REQUEST = 'ADD_CENTER_REQUEST';
export const ADD_CENTER_SUCCESS = 'ADD_CENTER_SUCCESS';
export const ADD_CENTER_FAIL = 'ADD_CENTER_FAIL';
export const CENTERS_LIST_REQUEST = 'CENTERS_LIST_REQUEST';
export const CENTERS_LIST_SUCCESS = 'CENTERS_LIST_SUCCESS';
export const CENTERS_LIST_FAIL = 'CENTERS_LIST_FAIL';
export const CENTERS_LIST_RESET = 'CENTERS_LIST_RESET';
