export const ADD_ENROLLEE_REQUEST = 'ADD_ENROLLEE_REQUEST';
export const ADD_ENROLLEE_SUCCESS = 'ADD_ENROLLEE_SUCCESS';
export const ADD_ENROLLEE_FAIL = 'ADD_ENROLLEE_FAIL';

export const EDIT_ENROLLEE_REQUEST = 'EDIT_ENROLLEE_REQUEST';
export const EDIT_ENROLLEE_SUCCESS = 'EDIT_ENROLLEE_SUCCESS';
export const EDIT_ENROLLEE_FAIL = 'EDIT_ENROLLEE_FAIL';
export const EDIT_ENROLLEE_RESET = 'EDIT_ENROLLEE_RESET';

export const ENROLLEE_DETAILS_REQUEST = 'ENROLLEE_DETAILS_REQUEST';
export const ENROLLEE_DETAILS_SUCCESS = 'ENROLLEE_DETAILS_SUCCESS';
export const ENROLLEE_DETAILS_FAIL = 'ENROLLEE_DETAILS_FAIL';
export const ENROLLEE_DETAILS_RESET = 'ENROLLEE_DETAILS_RESET';

export const ENROLLEES_LIST_REQUEST = 'ENROLLEES_LIST_REQUEST';
export const ENROLLEES_LIST_SUCCESS = 'ENROLLEES_LIST_SUCCESS';
export const ENROLLEES_LIST_FAIL = 'ENROLLEES_LIST_FAIL';
export const ENROLLEES_LIST_RESET = 'ENROLLEES_LIST_RESET';
